

SELECT COUNT(*) FROM [LDM_PROD_TD_GB_WM_VM].[rewards].[vwSKU_DLY_POS_UNPIVOT_ADJ] 
where GREGORIAN_DATE >= '2021-12-01' AND GREGORIAN_DATE <= '2021-12-07';

SELECT COUNT(*) FROM [LDM_PROD_TD_GB_WM_VM].[rewards].[vwSKU_DLY_POS_UNPIVOT_ADJ] 
where GREGORIAN_DATE >= '2021-12-08' AND GREGORIAN_DATE <= '2021-12-14';

SELECT COUNT(*)
FROM [LDM_PROD_TD_GB_WM_VM].[rewards].[vwSKU_DLY_POS_UNPIVOT_ADJ] 
where GREGORIAN_DATE >= '2022-02-01' AND GREGORIAN_DATE <= '2022-02-28'
--SELECT top 10 * FROM [LDM_PROD_TD_GB_WM_VM].[rewards].[vwSKU_DLY_POS_UNPIVOT_ADJ]